version:                2
jobs:
  build:
    docker:
      - image:          circleci/golang:1.8

    working_directory:  /go/src/github.com/scompo/product-inventory
    steps:
      - checkout

      - run:            go get -v -t -d ./...
      - run:            go get github.com/jstemmer/go-junit-report
      - run:            go test -v ./...

      - store_test_results:
          path:         /tmp/test-results
